GET http://localhost:3003/api/blogs

###
PUT http://localhost:3003/api/blogs/6008847232983d055c064xxx
Content-Type: application/json

{
    "likes": 99,
    "title": "Test3",
    "author": "Marcus Grenier II",
    "url": "http://www.mediumblog.com/articles/psbpII"
}

###
// Add user
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "hikerholloway",
    "name": "Mini Blessed",
    "password": "rushyBooBoo"
}

###
// Login
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "hikerholloway",
    "password": "rushyBooBoo"
}

###
// Add new blog under user's account
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imhpa2VyaG9sbG93YXkiLCJpZCI6IjYwMTA3MTVjMGVhMDA0MDJjNGEyNTY4OSIsImlhdCI6MTYxMTgwMDcwNX0.p1-bjskar6xgKgO4eE5mEzP5ZkT8LGltbkNaZh_7RfY

{
    "title": "Single Page Apps and token authentication",
    "author": "M. Nite Shamalamalon",
    "url": "http://www.mediumblog.com/articles/tokenbased",
    "likes": 21
}

###
// Delete a blog under user's account
DELETE http://localhost:3003/api/blogs/6012280e59ea6643b8a1739c
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imhpa2VyaG9sbG93YXkiLCJpZCI6IjYwMTA3MTVjMGVhMDA0MDJjNGEyNTY4OSIsImlhdCI6MTYxMTgwMjUxNn0.ySRHqDvN6KZlif19Dk9b52G7m3QQ3AtCFn8oDlrm94g

